S5 us19 testimony
WildCodeSchool/orleans-202103-php-project-bretin pull request #108
Opened 2021-07-01 10:28 UTC by NEL45

2021-07-01 12:58 UTC, Mcbess-san approved these changes

2021-07-01 12:58 UTC, jfillion12394 approved these changes

2021-07-01 13:13 UTC, sblondeau requested changes
là tu as seulement généré un CRUD non ? je ne vois aucune modif par rapport au make:crud
Ton US est
US 19 en tant qu'admin je veux pouvoir lister les avis clients afin d'avoir des retours d'expérience #63 
=> donc génération du CRUD mais surtout mise en forme de la partie listant les avis clients coté admin, ce qui entraine
- dans le controller, un findBy() pour classer peut-etre par date ? (là pas de classement)
- dans index.html => mise en forme et traduction
et le reste tu n'y touches pas maintenant car ce sont des autres US, mais tu peux push quand meme les fichiers générés

2021-07-02 10:48 UTC, Mcbess-san approved these changes

2021-07-02 15:56 UTC, sblondeau requested changes

2021-07-02 15:56 UTC, sblondeau commented on migrations/Version20210702084036.php
> +final class Version20210702084036 extends AbstractMigration
non il ne faut pas systématiquement effacer les migration et les recréer ! vous etes embetez à chaque fois sinon. Les migrations doivent se cumuler. Dans ton fichier, tu ne dois avoir que les requetes SQL propres à ton US si celle-ci modifie la structure de la BDD

2021-07-04 22:43 UTC, NEL45 commented on migrations/Version20210702084036.php
> +final class Version20210702084036 extends AbstractMigration
J'ai effectué la modification. J'ai actuellement mon ancien fichier de migration et le nouveau concernant mon entity Testimony.

2021-07-05 07:21 UTC, Mcbess-san approved these changes

2021-07-05 07:25 UTC, sblondeau approved these changes

2021-07-05 07:25 UTC, merged