Fix activity
WildCodeSchool/orleans-202103-php-project-bretin pull request #111
Opened 2021-07-01 14:15 UTC by NEL45

2021-07-01 14:41 UTC, Mcbess-san requested changes

2021-07-01 14:41 UTC, Mcbess-san commented on tatus
> +  dev[m
supprime le fichier tatus ?

2021-07-02 10:31 UTC, NEL45 commented on tatus
> +  dev[m
Oui, je ne comprend pas pourquoi et où il a été généré

2021-07-02 10:39 UTC, NEL45 commented on tatus
> +  dev[m
Mais c'est bon le nécessaire est fait

2021-07-02 10:49 UTC, Mcbess-san approved these changes

2021-07-02 15:58 UTC, sblondeau approved these changes

2021-07-02 15:58 UTC, merged