validion form
WildCodeSchool/orleans-202103-php-project-bretin pull request #118
Opened 2021-07-02 09:03 UTC by Mcbess-san

2021-07-02 09:11 UTC, jfillion12394 approved these changes

2021-07-02 16:01 UTC, sblondeau requested changes

2021-07-02 16:01 UTC, sblondeau commented on src/Entity/Education.php
> +     * @Assert\NotBlank(message="Veuillez saisir une année")
tu peux ajouter une validation pour t'assurer que la valeur est comprise entre 1900 et 2100 par exemple, ça me semble une fourchette raisonnable
tout du moins vérifier que c'est un entier positif

2021-07-05 07:35 UTC, sev-30 approved these changes

2021-07-05 07:36 UTC, jfillion12394 approved these changes

2021-07-05 07:39 UTC, sblondeau approved these changes

2021-07-05 07:39 UTC, merged