affichage services
WildCodeSchool/orleans-202103-php-project-bretin pull request #127
Opened 2021-07-05 09:15 UTC by sev-30

2021-07-05 09:40 UTC, Mcbess-san approved these changes

2021-07-05 10:33 UTC, sblondeau approved these changes

2021-07-06 07:27 UTC, Mcbess-san approved these changes

2021-07-06 10:01 UTC, sblondeau requested changes

2021-07-06 10:01 UTC, sblondeau commented on src/Entity/Service.php
> +    public function getPrice(): ?int
ils servent à quoi price et price2 car tu ne t'en sers pas à l'affichage

2021-07-06 10:01 UTC, sblondeau commented on templates/Individuals/index.html.twig
> +			<div class="col-12 col-md-6 col-lg-3">
pas de col-12 (à enlever partout)

2021-07-06 13:42 UTC, Mcbess-san approved these changes

2021-07-06 15:19 UTC, sblondeau approved these changes

2021-07-06 15:20 UTC, merged