Testimony Edit
WildCodeSchool/orleans-202103-php-project-bretin pull request #144
Opened 2021-07-06 14:12 UTC by NEL45

2021-07-06 14:30 UTC, jfillion12394 approved these changes

2021-07-06 15:24 UTC, sblondeau requested changes

2021-07-06 15:24 UTC, sblondeau commented on src/Controller/TestimonyController.php
> +     * @Route("/{id}/Editer", name="testimony_edit", methods={"GET","POST"})
pas de majucule dans la route

2021-07-06 15:24 UTC, sblondeau commented on src/Form/TestimonyType.php
> +            'placeholder' => 'nom'
c'est plutot les label que tu fais ici ? (mais tu le fais dans le Twig en fait)
si tu ajoutes des placeholder, ça doit plutot etre des exemples de données à saisir, pas ex 'John Doe'

2021-07-07 08:06 UTC, jfillion12394 approved these changes

2021-07-07 08:40 UTC, sblondeau requested changes

2021-07-07 08:40 UTC, sblondeau commented on src/Form/TestimonyType.php
> +        ->add('name', null, array('attr' => array(
[] pas array()

2021-07-07 12:14 UTC, jfillion12394 approved these changes

2021-07-07 12:26 UTC, sblondeau approved these changes

2021-07-07 12:41 UTC, jfillion12394 approved these changes

2021-07-07 12:43 UTC, sblondeau approved these changes

2021-07-07 12:43 UTC, merged