spelling mistake
WildCodeSchool/orleans-202103-php-project-bretin pull request #160
Opened 2021-07-07 13:07 UTC by NEL45

2021-07-07 20:13 UTC, Mcbess-san approved these changes

2021-07-08 06:51 UTC, sblondeau requested changes
tu as relus ta phrase ? ça n'a ni queue ni tete, y a deux phrases mélangées qui se répètent.
Et le mot "mutueliste" n'existe pas :o

2021-07-08 12:26 UTC, jfillion12394 approved these changes

2021-07-08 12:59 UTC, sblondeau approved these changes

2021-07-08 12:59 UTC, merged