Admin
WildCodeSchool/orleans-202103-php-project-bretin pull request #164
Opened 2021-07-08 09:42 UTC by jfillion12394

2021-07-08 10:06 UTC, Mcbess-san approved these changes

2021-07-08 11:34 UTC, sblondeau requested changes

2021-07-08 11:34 UTC, sblondeau commented on src/Entity/AdminUser.php
> +class AdminUser implements UserInterface
pourquoi AdminUser alors que tu as déjà une entity User ?

2021-07-08 11:34 UTC, sblondeau commented on src/Entity/AdminUser.php
> +    private string $Email;
attention, $email et pas $Email

2021-07-08 12:09 UTC, jfillion12394 commented on src/Entity/AdminUser.php
> +class AdminUser implements UserInterface
En fait la table user d'origine est mal nommée car elle contient les infos sur la biographie. Elle aurait dû s'apeler plutpt bio ou biography je pense.
alors que admin_user est spécifique et compte et infos d'admin.

2021-07-08 12:38 UTC, sev-30 commented on templates/Includes/admin.html.twig
> +                            <a href="" class="btn btn-primary">G&Eacute;RER LES COORDONN&Eacute;ES DE VOS CABINETS</a><br>
remets le caractère majuscule en dur plutot que le code html, c'est bizzare ainsi...

2021-07-08 13:02 UTC, sblondeau requested changes

2021-07-08 13:02 UTC, sblondeau commented on src/Entity/AdminUser.php
> +class AdminUser implements UserInterface
non non, la table User contient les infos sur le User, la biography y a tout à fait sa place. 
Comme on en a parlé hier ou avant-hier je ne sais plus, toi tu dois créer normalement une table User et fusionner l'existante.
 Bref, en soit que tu l'ai appelée AdminUser n'est pas très grave, par contre il faut y rappatrié la biography et autre champs déjà créés, ça ça ne change pas !

2021-07-08 15:39 UTC, Mcbess-san approved these changes

2021-07-08 15:54 UTC, sblondeau requested changes

2021-07-08 15:54 UTC, sblondeau commented on src/Entity/AdminUser.php
> +     * @ORM\Column(type="string", length=180, unique=true)
manque un Assert\Length à 180

2021-07-08 15:54 UTC, sblondeau commented on src/Entity/AdminUser.php
> +     * @ORM\Column(type="string", length=255)
Assert\Length à 255

2021-07-08 15:54 UTC, sblondeau commented on templates/Includes/admin.html.twig
> +                    {% if app.user %}
tu me fais une espèce de navbar là ? il faudrait plutot un layoutAdmin avec une navbar propre à l'admin, mais c'est une autre US... j'ai trop de choses là

2021-07-08 15:54 UTC, sblondeau commented on templates/Includes/admin.html.twig
> +                         {% if app.user %}
cette pas ne sera accessible que si on est déjà authentifié (en tant qu'admin) donc pas là pein de mettre un if app.user car on est forcément connecté et donc y a forcément un app.user

2021-07-09 06:41 UTC, sblondeau approved these changes

2021-07-09 06:41 UTC, merged