Page entreprises services
WildCodeSchool/orleans-202103-php-project-bretin pull request #165
Opened 2021-07-08 12:27 UTC by sev-30

2021-07-08 12:33 UTC, jfillion12394 submitted a review, later dismissed

2021-07-08 13:04 UTC, sblondeau requested changes
encore des images trop grosses,  attention < 200ko

2021-07-08 13:04 UTC, sblondeau commented on templates/Companies/index.html.twig
> +							<br><img class="clipboard-check px-2" img src="{{ asset('build/images/clipboard-check.svg') }}" alt="clipboard-check_picture">La confidentialité
faudrait que tu me montres éventuellement, mais ça me parait bizarre toutes les images séparées par des br ?

2021-07-08 13:28 UTC, sev-30 commented on templates/Companies/index.html.twig
> +							<br><img class="clipboard-check px-2" img src="{{ asset('build/images/clipboard-check.svg') }}" alt="clipboard-check_picture">La confidentialité
pour gérer mes retours à la ligne
![icon](https://user-images.githubusercontent.com/75568227/124929925-2bd68400-e001-11eb-8ebf-55f9def64621.png)

2021-07-08 13:30 UTC, sev-30 commented on templates/Companies/index.html.twig
> +							<br><img class="clipboard-check px-2" img src="{{ asset('build/images/clipboard-check.svg') }}" alt="clipboard-check_picture">La confidentialité
et pour l'image trop grosse j'ai redimensionné j'arrive à 214 ko après en dessus j'impacte la résolution :/

2021-07-08 13:43 UTC, Mcbess-san submitted a review, later dismissed

2021-07-08 14:25 UTC, sblondeau requested changes

2021-07-08 14:25 UTC, sblondeau commented on templates/Companies/index.html.twig
> +							<br><img class="clipboard-check px-2" img src="{{ asset('build/images/clipboard-check.svg') }}" alt="clipboard-check_picture">La confidentialité
pour ton image, converti là en jpg (si pas besoin de transparence) ou en webp, tu vas gagner énormément
sinon là pour ce que tu veux faire, c'est un ul/li en fait qu'il te faut ! 
et tu peux meme direct en CSS lui mettre une image en puce https://developer.mozilla.org/fr/docs/Web/CSS/list-style, ça serait beaucoup plus simple

2021-07-08 18:15 UTC, Mcbess-san approved these changes

2021-07-09 06:42 UTC, sblondeau approved these changes

2021-07-09 06:42 UTC, merged