S06 us47 bannières espace particuliers
WildCodeSchool/orleans-202103-php-project-bretin pull request #183
Opened 2021-07-12 09:37 UTC by sev-30

2021-07-12 10:20 UTC, jfillion12394 submitted a review, later dismissed

2021-07-12 10:29 UTC, sblondeau requested changes

2021-07-12 10:29 UTC, sblondeau commented on assets/styles/companies.scss
> +    @media (min-width: 260px) and (max-width: 1400px) {
pourquoi la media query? et pourquoi tu aurais un min-width à 260 ? ça veut dire qu'en dessous de 260 tu ferais réapparaitre l'info ? 
les classes de bootstrap doivent etre suffisante

2021-07-12 10:29 UTC, sblondeau commented on assets/styles/individuals.scss
> +    @media (min-width: 260px) and (max-width: 1400px) {
idem

2021-07-12 10:29 UTC, sblondeau commented on migrations/Version20210709075125.php
> +        $this->addSql('CREATE TABLE admin_user (id INT AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, biography LONGTEXT NOT NULL, url VARC
migration inutile ici, enlève le fichier

2021-07-13 09:53 UTC, jfillion12394 approved these changes

2021-07-13 09:57 UTC, sblondeau approved these changes

2021-07-13 09:57 UTC, merged