Fix navbar target
WildCodeSchool/orleans-202103-php-project-bretin pull request #185
Opened 2021-07-12 10:07 UTC by sev-30

2021-07-12 10:18 UTC, jfillion12394 submitted a review, later dismissed

2021-07-12 10:32 UTC, sblondeau requested changes

2021-07-12 10:32 UTC, sblondeau commented on assets/styles/accueil.scss
> +    font-weight: bolder !important;
pas de !important !

2021-07-12 10:32 UTC, sblondeau commented on migrations/Version20210709075125.php
> +        // this up() migration is auto-generated, please modify it to your needs
fichier de migration inutile ici, à retirer

2021-07-12 13:48 UTC, sev-30 commented on assets/styles/accueil.scss
> +    font-weight: bolder !important;
je peux pas faire autrement, je suis obligée de surcharger :/

2021-07-13 10:41 UTC, NEL45 approved these changes

2021-07-13 11:33 UTC, sblondeau approved these changes

2021-07-13 11:33 UTC, merged