us 5 contact images
WildCodeSchool/orleans-202103-php-project-bretin pull request #21
Opened 2021-06-03 14:13 UTC by jfillion12394

US 5
voir les photos du cabinet | d'avoir un aperçu du lieu où se déroule les séances

2021-06-03 14:55 UTC, Mcbess-san approved these changes

2021-06-03 17:03 UTC, sblondeau approved these changes
1. les images sont beaucoup trop grosses, je rappelle, pas plus de 200ko
2. ta US est sensé aller prendre ses infos dans la table cabinet, donc il ne faut pas me mettre tout en dur. Tu dois créer l'entité, faire des fixtures, et afficher ce qu'il y a dans la table !

2021-06-07 07:44 UTC, sblondeau requested changes
je ne vois pas la différence avec la dernière fois ? :o tjs des grosses images, tjs pas d'entity

2021-06-07 07:44 UTC, sblondeau commented on templates/home/contact.html.twig
> +    <br><br><br><br><br>
pas de br pour faire des espacements verticaux
fais du css

2021-06-09 08:22 UTC, closed without merging