Fix routes fr
WildCodeSchool/orleans-202103-php-project-bretin pull request #210
Opened 2021-07-15 15:03 UTC by NEL45

2021-07-15 15:32 UTC, Mcbess-san submitted a review, later dismissed

2021-07-15 20:52 UTC, sblondeau requested changes

2021-07-15 20:52 UTC, sblondeau commented on src/Controller/SecurityController.php
> +     * @Route("/déconnexion", name="app_logout")
pas d'accent dans les routes

2021-07-15 20:52 UTC, sblondeau commented on src/Controller/TestimonyController.php
> + * @Route("/admin/témoignages")
pas d'accent => temoignages et non témoignages

2021-07-18 17:29 UTC, sev-30 approved these changes

2021-07-19 07:27 UTC, sblondeau approved these changes

2021-07-19 07:28 UTC, merged