fix flash message and nullable field
WildCodeSchool/orleans-202103-php-project-bretin pull request #211
Opened 2021-07-15 15:14 UTC by Mcbess-san

2021-07-15 15:17 UTC, jfillion12394 approved these changes

2021-07-15 20:51 UTC, sblondeau requested changes

2021-07-15 20:51 UTC, sblondeau commented on src/Entity/Contact.php
> +    private string $intervention;
hum non je pense qu'il faut garder les "?"
là si tu enlèves via la console les required sur les champs de ton form et que tu  valides, l'objet Command va etre hydraté avec "null" comme valeur et ça va planter si le type n'est pas nullable.
Ce qui ne t'empeche pas de mettre tes Assert\NotBlank qui renverrons une erreur "propre" sur ton form si le champ est obligatoire

2021-07-16 07:58 UTC, jfillion12394 approved these changes

2021-07-16 08:40 UTC, sblondeau approved these changes

2021-07-16 08:40 UTC, merged