Fix individuals formatting all
WildCodeSchool/orleans-202103-php-project-bretin pull request #219
Opened 2021-07-16 14:46 UTC by NEL45

2021-07-18 17:27 UTC, sev-30 approved these changes

2021-07-19 07:23 UTC, sblondeau requested changes

2021-07-19 07:23 UTC, sblondeau commented on assets/styles/testimony.scss
> +// #scale {
pas de code commenté

2021-07-20 07:26 UTC, jfillion12394 approved these changes

2021-07-20 07:40 UTC, sblondeau approved these changes

2021-07-20 07:41 UTC, merged