footer
WildCodeSchool/orleans-202103-php-project-bretin pull request #242
Opened 2021-07-26 15:08 UTC by NEL45

2021-07-26 15:14 UTC, sev-30 approved these changes

2021-07-26 15:48 UTC, sblondeau requested changes

2021-07-26 15:48 UTC, sblondeau commented on templates/Includes/_footer.html.twig
>  		<address class="contacts text-center text-sm-start col-sm-3 col-md-2 col-lg-2 col-xl-2 pt-4">
mais attends, les données du footer ne viennent pas de la base de données ? avec les tables gérant justement les cabinets ?

2021-07-27 11:34 UTC, Mcbess-san approved these changes

2021-07-27 12:35 UTC, sblondeau requested changes

2021-07-27 12:35 UTC, sblondeau commented on templates/Includes/_footer.html.twig
>  			1 Rue Courcaille,<br>
il faut que tu récupères tes cabinets et que tu fasses une boucle dessus puis afficher ce qui vient de la BDD. Regarde ça avec Joel si tu veux, vu que c'est lui qui a fait l'entity là dessus

2021-07-27 12:35 UTC, sblondeau commented on templates/Includes/_footer.html.twig
> +			<br><br>
un simple br pour un retour à la ligne ça passe, mais pas de double br, si tu veux faire plus d'espacement vertical, fait du CSS

2021-07-27 14:27 UTC, Mcbess-san approved these changes

2021-07-28 07:55 UTC, jfillion12394 approved these changes

2021-07-28 07:57 UTC, sblondeau approved these changes

2021-07-28 07:57 UTC, merged