fix button class RDV
WildCodeSchool/orleans-202103-php-project-bretin pull request #35
Opened 2021-06-08 07:58 UTC by sev-30

2021-06-09 08:21 UTC, jfillion12394 approved these changes

2021-06-09 09:21 UTC, sblondeau requested changes

2021-06-09 09:21 UTC, sblondeau commented on assets/styles/app.scss
> +@media screen and (max-width: 460px)
pourquoi cacher le navbar brand sur petit écran ? tu es en mode burger là donc le logo ne devrait pas géner ? 
il faut le laisser. et dans tous les cas si tu as vraiment besoin de faire ça, tu peux faire un d-none d-sm-block

2021-06-09 10:19 UTC, Mcbess-san approved these changes

2021-06-09 13:29 UTC, sblondeau requested changes

2021-06-09 13:29 UTC, sblondeau commented on templates/Includes/_navbar.html.twig
> +            <button class="btn">Prise de RDV</button>
pourquoi vous passez le lien en form ? ça n'a pas de sens.
Si c'est juste pour donner une tete de bouton, il suffit de mettre une classe btn sur le lien

2021-06-10 15:20 UTC, Mcbess-san approved these changes

2021-06-10 15:29 UTC, Mcbess-san approved these changes

2021-06-10 15:56 UTC, sblondeau requested changes

2021-06-10 15:56 UTC, sblondeau commented on assets/styles/app.scss
> +.btn{
non tu ne dois pas surcharger btn !
dans bootstrap, pour un bouton tu dois faire class="btn btn-primary"
vu que tu as surchargé $primary ça doit fonctionner, pas besoin du hover en dessous non plus normalement

2021-06-11 07:32 UTC, jfillion12394 submitted a review, later dismissed

2021-06-11 08:35 UTC, sblondeau requested changes

2021-06-11 08:35 UTC, sblondeau commented on templates/Includes/_navbar.html.twig
> +          <a href="https://www.doctolib.fr/psychologue/orleans/loic-bretin" <button type="button" class="btn btn-primary">Prise de RDV</button></a>
non, jamais de button dans un lien, utilise les classes btn de bootstrap

2021-06-11 18:56 UTC, Mcbess-san approved these changes

2021-06-13 21:53 UTC, sblondeau approved these changes

2021-06-13 21:53 UTC, merged