S03_US01_Footer
WildCodeSchool/orleans-202103-php-project-bretin pull request #37
Opened 2021-06-09 14:49 UTC by NEL45

2021-06-09 14:57 UTC, sev-30 submitted a review, later dismissed

2021-06-09 18:40 UTC, jfillion12394 submitted a review, later dismissed

2021-06-09 18:44 UTC, jfillion12394 commented
Nicolas, il faut que tu relances ton commit  car tu as des erreurs de build.

2021-06-10 07:54 UTC, sev-30 approved these changes

2021-06-10 09:49 UTC, sblondeau requested changes

2021-06-10 09:49 UTC, sblondeau commented on templates/Includes/test.html.twig
> +<!-- Footer -->
attention fichier qui ne devrait pas etre là, à supprimer

2021-06-10 12:31 UTC, NEL45 commented on templates/Includes/test.html.twig
> +<!-- Footer -->
Oui, le fichier est supprimé

2021-06-10 13:20 UTC, sev-30 approved these changes

2021-06-10 13:30 UTC, sblondeau approved these changes

2021-06-10 13:30 UTC, merged