Contact
WildCodeSchool/orleans-202103-php-project-bretin pull request #39
Opened 2021-06-10 15:35 UTC by jfillion12394

2021-06-10 16:01 UTC, jfillion12394 commented
user story redéfin pour prendre en compte que la creation de la page contact avec list des cabinets.

2021-06-10 17:45 UTC, Mcbess-san commented on .env
> +DATABASE_URL="mysql://db_user:db_password@127.0.0.1:3306/bretin_db?serverVersion=8.0"
c'est dans ton fichier .env.local que tu dois modifier le nom de la bdd joël !

2021-06-10 17:47 UTC, Mcbess-san commented on assets/styles/variables.scss
> -$tertiary: #6e9a88;
pourquoi l'enlever ?

2021-06-10 17:50 UTC, Mcbess-san commented on templates/home/contact.html.twig
> +<div class =) "container-fluid">
une parenthèse à enlever

2021-06-10 17:51 UTC, Mcbess-san requested changes
regarder les commentaires laisser sur les fichiers

2021-06-10 19:03 UTC, Mcbess-san requested changes

2021-06-10 19:03 UTC, Mcbess-san commented on .gitignore
> +/.env
à enlever sinon tout le reste c'est good

2021-06-11 18:58 UTC, Mcbess-san submitted a review, later dismissed

2021-06-13 21:57 UTC, sblondeau requested changes

2021-06-13 21:57 UTC, sblondeau commented on migrations/Version20210611150810.php
> +namespace DoctrineMigrations;
cette migration retire la talbe picture. Mais en l'état du projet, si qq'un d'autre lance cette migration ça va placer vu qu'il n'aura pas de table picture à supprimer !
il me faut juste la migration qui créé la table office

2021-06-13 21:57 UTC, sblondeau commented on src/DataFixtures/AppFixturesOffice.php
> +class AppFixturesOffice extends Fixture
OfficeFixtures et non AppFixutresOffice

2021-06-13 21:57 UTC, sblondeau commented on src/Controller/ContactController.php
> +    private static function getOffices(ContactController $thisCollection): array
cette methode privée ne sert à rien ici. Tu ferais mieux d'injecter OfficeRepository en param de ta methode index() et faire ton findAll() direct dans index()

2021-06-16 10:10 UTC, Mcbess-san approved these changes

2021-06-16 13:26 UTC, sblondeau approved these changes

2021-06-16 13:26 UTC, merged