bouton prise de rdv fix
WildCodeSchool/orleans-202103-php-project-bretin pull request #77
Opened 2021-06-22 09:11 UTC by sev-30

2021-06-22 13:30 UTC, NEL45 approved these changes

2021-06-22 14:49 UTC, sblondeau requested changes

2021-06-22 14:49 UTC, sblondeau commented on migrations/Version20210618152501.php
> +<?php
je n'ai pas à avoir une migration ici, si c'est un fix de navbar

2021-06-23 07:03 UTC, sev-30 commented on migrations/Version20210618152501.php
> +<?php
oui j'ai pas compris pourquoi ell est partie aussi surtout que j'ai sélectionné en git add juste le fichier style

2021-06-23 10:18 UTC, closed without merging