Flash
WildCodeSchool/orleans-202103-php-project-bretin pull request #90
Opened 2021-06-24 13:21 UTC by jfillion12394

2021-06-24 14:07 UTC, Mcbess-san approved these changes

2021-06-24 15:44 UTC, sblondeau requested changes

2021-06-24 15:44 UTC, sblondeau commented on templates/base_admin.html.twig
> +        {% block flash %}
pb d'indentation.
Mais sinon, c'est plutot dans base et non dans base_admin que tu devrais le mettre, tu auras potentiellement besoin de message flash sur les pages visiteurs (confirmation de form de contact par ex)

2021-06-25 15:01 UTC, Mcbess-san approved these changes

2021-06-25 15:02 UTC, sblondeau approved these changes

2021-06-25 15:02 UTC, merged